spring:
  application:
    name: agent
  # 配置postgresql数据库连接
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${POSTGRESQL_PASSWORD:123456789rj}
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5-coder:7b
          temperature: 0.2
          top-p: 0.3
          max-tokens: 4096
      embedding:
        options:
          model: nomic-embed-text:latest
      init:
        timeout: 300s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Redis 连接配置（sa-token token 默认存储在此）
spring.data.redis:
  host: localhost
  port: 6379
  timeout: 5000ms
  database: 6
  password: ${REDIS_PASSWORD:20050603RJ}

# 配置sa-token
sa-token:
  token-name: rj-token
  timeout: 86400 # token有效期 24h
  is-concurrent: true # 是否允许同一账号多设备登录
  token-style: uuid
  is-log: true
server:
  port: 8099

